version: "3.8"
services:
  nginx1:
    image: nginx:latest
    ports:
      - 8001:80
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d

  nginx2:
    image: nginx:latest
    ports:
      - 8002:80
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
